apiVersion: apps/v1            # Specifies the API version for the resource. 'apps/v1' is used for Deployments.
kind: Deployment               # Defines the kind of resource. Here, it's a Deployment.
metadata:
  name: netflix-clone-deployment      # The name of the Deployment. This should be unique within the namespace.
  namespace: netflix-clone
  labels:
    app: netflix-clone          # A label applied to the Deployment to identify the application.
spec:
  replicas: 3                   # The number of pod replicas that the Deployment should maintain at all times.
  selector:
    matchLabels:
      app: netflix-clone        # Selector to match pods based on the label. The Deployment will manage all pods with this label.
  template:                    # Defines the template for the pods that will be created by this Deployment.
    metadata:
      labels:
        app: netflix-clone      # Labels applied to the pods created by this Deployment. These should match the selector labels.
    spec:
      containers:                           # Specifies the list of containers that will run in each pod.
      - name: netflix-clone                  # The name of the container, used for identification within the pod.
        image: dhairyap298/netflix-clone:3.0.0     # The Docker image to use for the container.
        ports:
        - containerPort: 3000               # The port that the container will expose to the network.

